### ISSUE TITLE
Make timestamp struct accessible/add trait to access components of the TimeStamp.

### ISSUE THREAD

**Issue by ridefox-ahirani** [tsabelmann/pcan-basic#1]
https://github.com/tsabelmann/pcan-basic/blob/0c589fda458a5f593a9feb02c4ed84a37bfd0bd6/src/lib.rs#L244

What is the bug: Cannot access info stored in the Timestamp.

Suggested fix: Make L244 `pub` or add a trait which enables access to the underlying timestamp.

**Comment by tsabelmann** [comment]
Hi there! I am currently working on a new iteration of `pcan-basic` to support almost any feature of the original `PCANBasic.h` header. Currently, I prefer to add a trait implementation to access the underlying timestamp. As of now, I do not know when I find the time to work at `pcan-basic` again, probably next weekend.

**Comment by ridefox-ahirani** [comment]
Hey! If you make an issue outlining the roadmap, I don't mind helping out implement some of it in my own fork.

**Comment by tsabelmann** [comment]
Hey! Thank you for your offer. I would like someone to review the next version of `pcan-basic` such that we can adapt and enhance the next version. I have already implemented most functionalities. Just some documentation, examples, etc. are missing. If you want, you can have a look at the next version, probably out next or the week after that.
