### ISSUE TITLE
LNK1181: cannot open input file 'PCANBasic.lib'

### ISSUE THREAD

**Issue by shanemmattner** [tsabelmann/pcan-basic#4]
Hello,
I'm trying to build [this example](https://github.com/tsabelmann/pcan-basic/blob/main/examples/recv_1.rs) on Windows 10 but get the error `note: LINK : fatal error LNK1181: cannot open input file 'PCANBasic.lib'`.

I installed the drivers for PEAK-Basic API and logged out/back in.  In `C:\Program Files\PEAK-System\PEAK-Drivers` I have:
![image](https://user-images.githubusercontent.com/22162612/229006043-be98da38-3b68-4120-ba69-0d3fced1f779.png)
![image](https://user-images.githubusercontent.com/22162612/229006076-2347a6f0-8c46-4543-8b68-607202c51619.png)

Any ideas what I might be doing wrong?

**Comment by nguyenlkdn** [comment]
@shanemmattner I am not sure your environment but i guest you are compiling it directly on window prompt command 
you have to install https://www.peak-system.com/PCAN-Basic.239.0.html?&L=1 for "PCANBasic.lib"
![image](https://user-images.githubusercontent.com/6241638/229727861-4d8b9053-d050-475c-9a50-87b327d221ee.png)

extract then copy it to your clang include lib dir
![image](https://user-images.githubusercontent.com/6241638/229728265-d0c5b946-7676-4987-a117-cec0d57c6a70.png)

**Comment by shanemmattner** [comment]
@nguyenlkdn that worked!  Thank you for the prompt response!
